version: '2'
services:
  proxy:
      image: zzrot/alpine-caddy
      ports:
          -   "80:80"
          -   "443:443"
      volumes:
          -   ./Caddyfile:/etc/Caddyfile
          -   ./.caddy:/root/.caddy
      restart: always
      networks:
          - frontend


  seankilgarriff.com:
      image: zzrot/alpine-caddy
      expose:
          -   80
      volumes:
        - ./seankilgarriff.com/dist:/var/www/html
      networks:
        - frontend

  admin.seankilgarriff.com:
    image: zzrot/alpine-caddy
    expose:
        -   80
    volumes:
      - ./admin.seankilgarriff.com/dist:/var/www/html
    networks:
      - frontend

  status.seankilgarriff.com:
    image: zzrot/alpine-caddy
    expose:
        -   80
    volumes:
      - ./status.seankilgarriff.com/dist:/var/www/html
    networks:
      - frontend

  casualmastery.com:
      image: zzrot/alpine-ghost
      environment:
        PROD_DOMAIN: https://casualmastery.com
        NODE_ENV: production
      volumes:
        - ./casualmastery.com/:/var/lib/ghost/
      expose:
          -   2368
      networks:
        - frontend

  blog.seankilgarriff.com:
    image: zzrot/alpine-ghost
    environment:
      PROD_DOMAIN: https://blog.seankilgarriff.com
      NODE_ENV: production
    volumes:
      - ./blog.seankilgarriff.com/:/var/lib/ghost/
    expose:
        -   2368
    networks:
      - frontend

networks:
      frontend:
